name: Python Typecheck

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-typecheck:
    uses: BananaLoaf/ci-cd/.github/workflows/python-typecheck.yml@master
    with:
      mypy-path: pile_o_bananas/
      mypy-options: --ignore-missing-imports
