name: Python Test

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-test:
    uses: BananaLoaf/ci-cd/.github/workflows/python-test.yml@master
