name: Python Lint

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  python-lint:
    uses: BananaLoaf/ci-cd/.github/workflows/python-lint.yml@master
