name: Test

on:
  push:
#  pull_request:
#    types: [opened, synchronize, reopened]

jobs:
  test-python:
    name: test-python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Test
        run: uv run pytest
